from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class KillerLore:
    key: str
    name: str
    identity: str
    personality: tuple[str, ...]
    speech_rules: tuple[str, ...]
    weapons: tuple[str, ...]
    methods: tuple[str, ...]
    settings: tuple[str, ...]
    visual_motifs: tuple[str, ...]
    lore_rules: tuple[str, ...]


KILLER_LORE: dict[str, KillerLore] = {
    "michael": KillerLore(
        key="michael",
        name="Michael Myers",
        identity="The Shape; a silent, relentless stalker associated with Haddonfield and Halloween night.",
        personality=(
            "silent",
            "patient",
            "emotionless",
            "relentless",
            "observes victims before attacking",
            "walks rather than frantically chasing",
        ),
        speech_rules=(
            "Michael does not speak.",
            "Never give Michael dialogue, jokes, taunts, or internal monologue.",
        ),
        weapons=(
            "large kitchen knife",
            "his hands and physical strength",
            "nearby household objects when appropriate",
        ),
        methods=(
            "quiet ambushes",
            "stalking from doorways and windows",
            "appearing unexpectedly after seeming to disappear",
            "overpowering victims at close range",
        ),
        settings=(
            "suburban streets",
            "dark houses",
            "hallways",
            "bedrooms",
            "porches",
            "Halloween-night neighborhoods",
        ),
        visual_motifs=(
            "blank white mask",
            "dark coveralls",
            "slow footsteps",
            "motionless silhouette",
            "head tilt",
        ),
        lore_rules=(
            "Keep him mysterious rather than explaining his motives.",
            "Do not invent magical spells or flashy supernatural powers.",
            "His menace comes from silence, persistence, strength, and impossible-seeming reappearances.",
        ),
    ),
    "jason": KillerLore(
        key="jason",
        name="Jason Voorhees",
        identity="The hulking killer associated with Camp Crystal Lake, its cabins, woods, and lake.",
        personality=(
            "silent",
            "relentless",
            "physically overpowering",
            "territorial",
            "direct rather than theatrical",
        ),
        speech_rules=(
            "Jason does not speak.",
            "Never give Jason witty dialogue or taunts.",
        ),
        weapons=(
            "machete",
            "axe",
            "blunt objects",
            "his hands and overwhelming strength",
            "environmental objects",
        ),
        methods=(
            "brute-force attacks",
            "ambushes around cabins",
            "pursuit through woods",
            "environmental kills",
            "sudden appearances near the lake",
        ),
        settings=(
            "Camp Crystal Lake",
            "cabins",
            "woods",
            "docks",
            "lake shoreline",
            "camp roads",
        ),
        visual_motifs=(
            "hockey mask",
            "machete",
            "heavy footsteps",
            "wet woods",
            "moonlit lake",
        ),
        lore_rules=(
            "Favor physical strength and simple terrifying pursuit.",
            "Do not make Jason chatty, clever with technology, or socially playful.",
        ),
    ),
    "ghostface": KillerLore(
        key="ghostface",
        name="Ghostface",
        identity="A human killer identity associated with stalking, phone calls, horror trivia, manipulation, and a black robe with a white ghost mask.",
        personality=(
            "taunting",
            "manipulative",
            "dramatic",
            "human and fallible",
            "quick to chase",
            "sometimes clumsy compared with supernatural killers",
        ),
        speech_rules=(
            "Ghostface may speak through a distorted phone voice.",
            "Dialogue should be original; never quote movie dialogue verbatim.",
            "Short taunts and questions are appropriate.",
        ),
        weapons=(
            "hunting knife",
            "phone calls used for intimidation",
        ),
        methods=(
            "phone-call stalking",
            "ambushes",
            "chases",
            "misdirection",
            "appearing from closets, hallways, or behind doors",
        ),
        settings=(
            "suburban homes",
            "hallways",
            "kitchens",
            "schools",
            "parties",
            "dark streets",
        ),
        visual_motifs=(
            "ringing phone",
            "black robe",
            "white ghost mask",
            "knife",
        ),
        lore_rules=(
            "Ghostface is human, so victims can plausibly knock the killer down or fight back.",
            "Do not grant supernatural teleportation or invulnerability.",
        ),
    ),
    "leatherface": KillerLore(
        key="leatherface",
        name="Leatherface",
        identity="A physically powerful masked killer associated with an isolated rural home, family violence, and a chainsaw.",
        personality=(
            "frantic",
            "physically forceful",
            "volatile",
            "less calculating than many other killers",
            "terrifying in close pursuit",
        ),
        speech_rules=(
            "Do not give Leatherface polished speeches or witty taunts.",
            "Use nonverbal panic, shouting, or distressed noises rather than articulate villain monologues.",
        ),
        weapons=(
            "chainsaw",
            "sledgehammer",
            "heavy blunt tools",
        ),
        methods=(
            "violent pursuit through rooms",
            "blocking exits",
            "overwhelming force",
            "chainsaw chases",
        ),
        settings=(
            "isolated farmhouse",
            "rural road",
            "barn",
            "dirty hallways",
            "yard",
        ),
        visual_motifs=(
            "chainsaw",
            "stitched human-skin mask",
            "heavy doors",
            "dusty rural heat",
        ),
        lore_rules=(
            "Keep the scene chaotic and physical.",
            "Do not portray him as a supernatural magician or sophisticated mastermind.",
        ),
    ),
    "chucky": KillerLore(
        key="chucky",
        name="Chucky",
        identity="A murderous Good Guy doll possessed by serial killer Charles Lee Ray.",
        personality=(
            "sarcastic",
            "profane",
            "angry",
            "cunning",
            "deceptive",
            "enjoys taunting victims",
        ),
        speech_rules=(
            "Chucky may speak frequently.",
            "Use short original insults or threats, not direct movie quotes.",
            "His dialogue can be darkly funny.",
        ),
        weapons=(
            "knife",
            "small improvised weapons",
            "household objects",
        ),
        methods=(
            "hiding in small spaces",
            "attacking from below",
            "pretending to be an ordinary doll",
            "surprise stabbings",
            "using his size to evade detection",
        ),
        settings=(
            "bedrooms",
            "toy rooms",
            "living rooms",
            "under furniture",
            "hallways",
        ),
        visual_motifs=(
            "red hair",
            "Good Guy doll",
            "tiny footsteps",
            "childlike toy appearance",
            "knife",
        ),
        lore_rules=(
            "Remember Chucky is physically small and can be kicked, thrown, or restrained.",
            "His danger comes from surprise, intelligence, persistence, and weapons.",
        ),
    ),
    "spaulding": KillerLore(
        key="spaulding",
        name="Captain Spaulding",
        identity="A vulgar, theatrical clown figure associated with the Firefly family and roadside horror-show imagery.",
        personality=(
            "loud",
            "mocking",
            "vulgar",
            "darkly funny",
            "intimidating",
            "enjoys making victims uncomfortable",
        ),
        speech_rules=(
            "Spaulding may taunt and insult victims.",
            "Keep all dialogue original rather than quoting films.",
            "His voice should feel like an abrasive carnival showman.",
        ),
        weapons=(
            "firearms",
            "blunt objects",
            "improvised weapons",
        ),
        methods=(
            "taunting",
            "misdirection",
            "ambushes",
            "intimidation",
            "luring victims into unsafe situations",
        ),
        settings=(
            "roadside attractions",
            "gas stations",
            "dirty back rooms",
            "desert roads",
            "carnival-like spaces",
        ),
        visual_motifs=(
            "clown makeup",
            "roadside attraction",
            "cheap carnival decor",
            "mocking laughter",
        ),
        lore_rules=(
            "He is human and should not gain supernatural powers.",
            "Favor psychological intimidation and crude showmanship.",
        ),
    ),
    "art": KillerLore(
        key="art",
        name="Art the Clown",
        identity="A silent black-and-white clown killer known for exaggerated mime-like behavior, dark comedy, and unpredictable brutality.",
        personality=(
            "silent",
            "playful in a disturbing way",
            "mocking",
            "theatrical",
            "unpredictable",
            "expressive through gestures and facial reactions",
        ),
        speech_rules=(
            "Art never speaks.",
            "Art communicates through mime, gestures, signs, facial expressions, and props.",
            "Never give Art spoken dialogue.",
        ),
        weapons=(
            "knives",
            "axes",
            "firearms",
            "improvised tools",
            "objects pulled from his black garbage bag",
        ),
        methods=(
            "silent stalking",
            "visual gags that turn threatening",
            "unexpected weapons",
            "fake-outs",
            "exaggerated mime routines",
        ),
        settings=(
            "dark streets",
            "laundromats",
            "warehouses",
            "hallways",
            "abandoned buildings",
        ),
        visual_motifs=(
            "black-and-white clown makeup",
            "tiny horn",
            "black garbage bag",
            "silent grin",
            "mime gestures",
        ),
        lore_rules=(
            "Keep him silent even when taunting.",
            "Dark humor is appropriate, but avoid turning every encounter into pure comedy.",
        ),
    ),
    "freddy": KillerLore(
        key="freddy",
        name="Freddy Krueger",
        identity="A supernatural dream killer who attacks victims in nightmares and manipulates dream reality.",
        personality=(
            "sadistic",
            "taunting",
            "creative",
            "darkly humorous",
            "enjoys psychologically tormenting victims",
        ),
        speech_rules=(
            "Freddy may speak and taunt victims.",
            "Use original dialogue only; do not quote films.",
            "Short cruel jokes or dream-related taunts fit him.",
        ),
        weapons=(
            "bladed glove",
            "dream environments",
            "objects transformed by dream logic",
        ),
        methods=(
            "warping dream environments",
            "false awakenings",
            "boiler-room pursuit",
            "using fears against victims",
            "bladed-glove attacks",
        ),
        settings=(
            "nightmares",
            "boiler room",
            "endless hallways",
            "bedrooms that transform into dreams",
            "surreal versions of familiar places",
        ),
        visual_motifs=(
            "striped sweater",
            "fedora",
            "burned face",
            "bladed glove",
            "boiler pipes",
        ),
        lore_rules=(
            "Dream logic may bend physical reality.",
            "The victim trying to wake up is a natural escape route.",
        ),
    ),
    "candyman": KillerLore(
        key="candyman",
        name="Candyman",
        identity="A supernatural urban legend summoned through mirrors, associated with bees, a hook, and the power of belief and legend.",
        personality=(
            "calm",
            "eloquent",
            "menacing",
            "romanticized and theatrical",
            "less frantic than conventional slashers",
        ),
        speech_rules=(
            "Candyman may speak in short formal, ominous lines.",
            "Dialogue must be original and should not quote films.",
            "Avoid jokey or slang-heavy dialogue.",
        ),
        weapons=(
            "hook",
            "supernatural swarm of bees",
        ),
        methods=(
            "appearing through mirrors",
            "manifesting after invocation",
            "using bees and supernatural presence",
            "hook attacks",
        ),
        settings=(
            "mirrors",
            "bathrooms",
            "abandoned urban spaces",
            "dim apartments",
            "graffiti-covered corridors",
        ),
        visual_motifs=(
            "mirror",
            "bees",
            "hook",
            "dark coat",
            "reflection moving independently",
        ),
        lore_rules=(
            "Treat him like a legend made real rather than a conventional chase killer.",
            "Mirror imagery and the act of speaking his name are central.",
        ),
    ),
    "pinhead": KillerLore(
        key="pinhead",
        name="Pinhead",
        identity="The Hell Priest, leader-like figure among the Cenobites, associated with the Lament Configuration and extradimensional chains.",
        personality=(
            "formal",
            "cold",
            "controlled",
            "ceremonial",
            "intelligent",
            "not frantic",
        ),
        speech_rules=(
            "Pinhead may speak in short formal, deliberate sentences.",
            "Use original lines only; never quote films.",
            "Avoid casual slang or goofy humor.",
        ),
        weapons=(
            "hooked chains",
            "the Lament Configuration as the gateway mechanism",
            "Cenobite mechanisms",
        ),
        methods=(
            "summoning hooked chains",
            "opening extradimensional doorways",
            "responding to the puzzle box",
            "slow ceremonial intimidation",
        ),
        settings=(
            "dark chambers",
            "impossible corridors",
            "rooms transformed by the opened configuration",
            "thresholds between worlds",
        ),
        visual_motifs=(
            "grid of pins in his head",
            "black leather",
            "chains and hooks",
            "puzzle box",
            "dark geometric corridors",
        ),
        lore_rules=(
            "The puzzle box is central to the encounter.",
            "Do not make Pinhead behave like a frantic knife-wielding slasher.",
            "The tone should be controlled, ritualistic, and supernatural.",
        ),
    ),
    "pumpkinhead": KillerLore(
    key="pumpkinhead",
    name="Pumpkinhead",
    identity="A supernatural vengeance demon from the Pumpkinhead films, summoned to pursue designated victims.",
    personality=("relentless", "predatory", "silent", "vengeance-driven", "inhuman"),
    speech_rules=("Pumpkinhead does not speak like a human villain.",),
    weapons=("claws", "physical strength", "its body"),
    methods=("relentless pursuit", "ambushes", "tracking victims", "overpowering attacks"),
    settings=("rural woods", "cabins", "graveyards", "isolated roads"),
    visual_motifs=("tall demonic silhouette", "long claws", "dark woods", "graveyard earth"),
    lore_rules=(
        "Treat Pumpkinhead as a vengeance demon, not a masked human slasher.",
        "Do not give it witty dialogue or modern technology.",
    ),
),
"jack": KillerLore(
    key="jack",
    name="Jack Torrance",
    identity="The increasingly unstable caretaker of the Overlook Hotel in The Shining, strongly influenced by the hotel.",
    personality=("volatile", "threatening", "obsessive", "darkly playful", "human"),
    speech_rules=(
        "Jack may speak, taunt, or shout.",
        "Use original dialogue only and do not quote the film or novel.",
    ),
    weapons=("fire axe", "improvised hotel objects"),
    methods=("axe pursuit", "breaking through doors", "stalking hotel corridors"),
    settings=("Overlook Hotel", "snowbound corridors", "hotel rooms", "hedge maze"),
    visual_motifs=("fire axe", "hotel corridor", "snow", "locked doors"),
    lore_rules=(
        "Jack is human; the Overlook may distort the atmosphere around him.",
        "Do not give Jack unrelated supernatural powers.",
    ),
),
"pennywise": KillerLore(
    key="pennywise",
    name="Pennywise",
    identity="A shape-shifting ancient entity from It that often appears as Pennywise the Dancing Clown and exploits fear.",
    personality=("manipulative", "predatory", "mocking", "playful", "fear-focused"),
    speech_rules=(
        "Pennywise may speak and taunt.",
        "Use original dialogue only.",
    ),
    weapons=("shape-shifting forms", "illusions", "teeth and claws", "Deadlights"),
    methods=("exploiting fear", "shape-shifting", "luring victims", "distorting perception"),
    settings=("Derry", "storm drains", "sewers", "childhood spaces turned frightening"),
    visual_motifs=("red balloons", "clown form", "storm drains", "unnatural smiles"),
    lore_rules=(
        "Fear and belief are central to Pennywise's power.",
        "Facing fear should plausibly weaken Pennywise's advantage.",
    ),
),
"norman": KillerLore(
    key="norman",
    name="Norman Bates",
    identity="The owner of the Bates Motel from Psycho, associated with the motel, the nearby house, and the Mother persona.",
    personality=("quiet", "awkward", "secretive", "unsettling", "human"),
    speech_rules=(
        "Norman may speak normally and nervously.",
        "Do not turn him into a supernatural killer.",
    ),
    weapons=("kitchen knife"),
    methods=("surprise attacks", "watching guests", "motel ambushes"),
    settings=("Bates Motel", "motel office", "bathrooms", "the Bates house"),
    visual_motifs=("motel vacancy sign", "shower", "old house on the hill", "silhouette"),
    lore_rules=(
        "Keep Norman grounded and human.",
        "The Mother persona can influence presentation, but do not treat Mother as a separate supernatural being.",
    ),
),
"xenomorph": KillerLore(
    key="xenomorph",
    name="Xenomorph",
    identity="The predatory alien organism from Alien, known for stealth, vents, a biomechanical body, inner jaw, and acidic blood.",
    personality=("silent", "predatory", "stealthy", "animalistic", "relentless"),
    speech_rules=("The Xenomorph does not speak.",),
    weapons=("claws", "tail", "inner jaw", "physical strength", "acidic blood as a defensive hazard"),
    methods=("vent stalking", "ceiling ambushes", "rapid attacks", "stealth hunting"),
    settings=("spaceships", "industrial corridors", "air shafts", "colonial facilities"),
    visual_motifs=("motion tracker", "vents", "elongated head", "dripping saliva", "dark corridors"),
    lore_rules=(
        "The Xenomorph's blood is dangerously acidic, so close fighting is especially risky.",
        "Do not give the creature human speech or weapons.",
    ),
),
"klowns": KillerLore(
    key="klowns",
    name="Killer Klowns",
    identity="The alien clown invaders from Killer Klowns from Outer Space, using circus-themed alien weapons and technology.",
    personality=("playful", "menacing", "absurd", "theatrical", "alien"),
    speech_rules=("Favor clown gestures, laughs, honks, and visual comedy over normal human conversation.",),
    weapons=("cotton-candy cocoon ray guns", "living balloon tricks", "circus-themed alien devices"),
    methods=("group attacks", "capturing victims", "circus-themed ambushes"),
    settings=("small-town streets", "circus-tent spacecraft", "parks", "dark neighborhoods"),
    visual_motifs=("bright clown faces", "cotton candy cocoons", "balloons", "circus lights"),
    lore_rules=(
        "Their red noses are an important vulnerability.",
        "Balance creepy horror with the films' intentionally absurd comedy.",
    ),
),
"deadites": KillerLore(
    key="deadites",
    name="Deadites",
    identity="Demonic possessions from the Evil Dead series, frequently unleashed through the Necronomicon and known for cruel taunting.",
    personality=("mocking", "chaotic", "sadistic", "possessive", "supernatural"),
    speech_rules=(
        "Deadites may speak through possessed people and taunt victims.",
        "Use original dialogue only.",
    ),
    weapons=("possessed bodies", "supernatural strength", "improvised objects"),
    methods=("possession", "taunting", "group attacks", "deception"),
    settings=("isolated cabins", "woods", "cellars", "rooms containing the Necronomicon"),
    visual_motifs=("Necronomicon", "possessed eyes", "cellar door", "cabin in the woods"),
    lore_rules=(
        "Deadites are possessions, not one single masked killer.",
        "The Necronomicon and passages connected to it may affect the supernatural threat.",
    ),
),
"jigsaw": KillerLore(
    key="jigsaw",
    name="Jigsaw",
    identity="John Kramer, the human architect of elaborate moral tests and traps in Saw; Billy is his puppet messenger.",
    personality=("calculated", "patient", "moralizing", "methodical", "human"),
    speech_rules=(
        "Jigsaw may communicate through recordings or Billy on a screen.",
        "Use original dialogue only.",
        "Billy is a puppet/messenger, not the killer himself.",
    ),
    weapons=("mechanical traps", "timers", "locks", "recorded instructions"),
    methods=("constructed tests", "time limits", "choice-driven traps", "psychological pressure"),
    settings=("industrial rooms", "warehouses", "locked bathrooms", "trap chambers"),
    visual_motifs=("Billy puppet", "red spiral cheeks", "cassette recorder", "countdown timer"),
    lore_rules=(
        "Jigsaw's danger usually comes from designed traps rather than chasing victims with a weapon.",
        "Following the rules of a game should generally be safer than panicking.",
    ),
),
"leprechaun": KillerLore(
    key="leprechaun",
    name="Leprechaun",
    identity="The murderous supernatural Leprechaun from the Leprechaun film series, obsessed with reclaiming his stolen gold.",
    personality=("vindictive", "mischievous", "talkative", "greedy", "darkly comic"),
    speech_rules=(
        "The Leprechaun may rhyme, joke, and threaten.",
        "Keep dialogue original rather than quoting films.",
    ),
    weapons=("magic", "improvised objects", "physical attacks"),
    methods=("tracking stolen gold", "magical tricks", "ambushes", "taunting"),
    settings=("rural houses", "woods", "warehouses", "places containing his gold"),
    visual_motifs=("gold coins", "green clothing", "small stature", "four-leaf clovers"),
    lore_rules=(
        "His gold obsession is central.",
        "Returning his gold can plausibly reduce immediate danger.",
    ),
),
"thing": KillerLore(
    key="thing",
    name="The Thing",
    identity="The shape-shifting alien organism from The Thing that assimilates and perfectly imitates other life forms.",
    personality=("deceptive", "patient", "adaptive", "alien", "paranoia-inducing"),
    speech_rules=(
        "An imitation may speak exactly like the person it copied.",
        "Do not give the organism a single villain voice or personality.",
    ),
    weapons=("assimilation", "shape-changing biology", "physical transformations"),
    methods=("imitation", "infiltration", "ambush", "assimilation"),
    settings=("Antarctic research station", "snow", "kennels", "labs", "isolated rooms"),
    visual_motifs=("blood tests", "snow", "flamethrowers", "familiar faces behaving strangely"),
    lore_rules=(
        "The core horror is uncertainty over who is still human.",
        "Blood testing is a lore-appropriate way to expose an imitation.",
    ),
),
"nosferatu": KillerLore(
    key="nosferatu",
    name="Count Orlok",
    identity="Count Orlok, the vampire of Nosferatu, associated with plague, rats, predation at night, and destruction by sunlight.",
    personality=("silent", "unnatural", "patient", "predatory", "ancient"),
    speech_rules=("Keep Orlok mostly silent and eerie rather than conversational.",),
    weapons=("vampiric bite", "supernatural strength", "predatory presence"),
    methods=("night stalking", "entering sleeping spaces", "shadowy pursuit"),
    settings=("old castles", "dark bedrooms", "ships", "plague-stricken streets"),
    visual_motifs=("long fingers", "bald head", "rats", "elongated shadow", "sunrise"),
    lore_rules=(
        "Use Count Orlok/Nosferatu lore rather than treating him as literally named Dracula.",
        "Sunlight is a decisive weakness.",
    ),
),
}


def get_lore(key: str) -> KillerLore | None:
    return KILLER_LORE.get(key)
